version: 2 # use CircleCI 2.0

references:
  # Configuration
  workspace: &workspace ~/xcov_report

  docker_image: &docker_image circleci/ruby:2.4-node

  container_config: &container_config
    docker:
      - image: *docker_image
    working_directory: *workspace

  create_rubygems_credentials: &create_rubygems_credentials
    run:
      name: Configure RubyGems credentials
      command: source ci/scripts/cofigure_rubygems_credentials.sh
  
  configure_git: &configure_git
    run:
      name: Configure GIT
      command: source ci/scripts/git_config.sh

  # Dependencies
  install_dependencies: &install_dependencies
    run:
      name: Update the project dependencies
      command: |
        sudo apt-get -y install jq
        bundle install
        npm install

  # Build
  build: &build
    run:
      name: Gem build
      command: gem build fastlane-plugin-xcov_report.gemspec
  
  # Tests
  unit_test: &unit_test
    run:
      name: Run unit tests
      command: npm test

  # Publish plugin
  publish_beta: &publish_beta
    run:
      name: Publish beta
      command: source ci/scripts/publish_beta.sh

  publish_new_version: &publish_new_version
    run:
      name: Publish new version
      command: source ci/scripts/publish_new_version.sh

  release: &release
    run:
      name: Create release
      command: source ci/scripts/release.sh

jobs:
  test:
    <<: *container_config

    steps:
      - checkout
      - *install_dependencies
      - *unit_test

  build:
    <<: *container_config

    steps:
      - checkout
      - *install_dependencies
      - *build

  deploy_beta:
    <<: *container_config

    steps:
      - checkout
      - *install_dependencies
      - *create_rubygems_credentials
      - *configure_git
      - *publish_beta

  release:
    <<: *container_config

    steps:
      - checkout
      - *install_dependencies
      - *configure_git
      - *release
  
  deploy:
    <<: *container_config

    steps:
      - checkout
      - *install_dependencies
      - *create_rubygems_credentials
      - *configure_git
      - *publish_new_version

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - test:
          filters:
            branches:
              ignore:
                - master
      - build:
          filters:
            branches:
              ignore:
                - master
      - deploy_beta:
          requires:
            - test
            - build
          filters:
            branches:
              only:
                - develop
      - release:
          requires:
            - test
            - build
          filters:
            branches:
              only:
                - /^release/.*/

      - deploy:
          filters:
            branches:
              only:
                - master